### ISSUE TITLE
No CI projects/builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/lz4-feedstock#1]
Seems this didn't get any CI projects added or builds created. Any ideas?

Also not sure if this is limited to this feedstock or if other feedstocks are having the same problem.

cc @conda-forge/core

**Comment by isuruf** [comment]
`pscript, pdal, molvs, logging_exceptions, cyclus-d3ploy` seems to have the issue as well

**Comment by jakirkham** [comment]
Great, was just about to ask that question. Will queue all of them up for a readd.

Do you want to go ahead and do a patch release of `conda-smithy`?

**Comment by isuruf** [comment]
@scopatz, can you do a patch release?

**Comment by scopatz** [comment]
Sure thing! But also note that I added release instructions to the readme https://github.com/conda-forge/conda-smithy#releasing-conda-smithy

**Comment by jakirkham** [comment]
Readding in PR ( https://github.com/conda-forge/staged-recipes/pull/5674 ). Please let me know if there is anything else needed in there.

**Comment by jakirkham** [comment]
This appears to have been resolved.
